apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    app: tripinsights-user-java

spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripinsights-user-java
  template:
    metadata:
      labels:
        app: tripinsights-user-java
    spec:
      containers:
      - name: tripinsights-user-java
        image: cropenhackcontainers2.azurecr.io/tripinsights/user-java:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        envFrom:
          - secretRef:
              name: secret-database
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
spec:
  selector:
    app: tripinsights-user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80