apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: c2550337-e0b7-448e-9345-3e2c24decf2d   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kvopenhackcontainers     # Set to the name of your key vault
    objects: |
      array:
        - |
          objectName: SQL-USER
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: SQL-PASSWORD
          objectType: secret
        - |
          objectName: SQL-SERVER
          objectType: secret
        - |
          objectName: SQL-DBNAME
          objectType: secret
    tenantId: 68fd421f-66ac-4aa8-af91-4a80d7e6f94a
  secretObjects:
  - data:
    - key: SQL_DBNAME
      objectName: SQL-DBNAME
    - key: SQL_SERVER
      objectName: SQL-SERVER
    - key: SQL_PASSWORD
      objectName: SQL-PASSWORD
    - key: SQL_USER
      objectName: SQL-USER
    secretName: secret-database
    type: Opaque